"""Django scaffolding is generated by substitution, never written by the model.

Six consecutive live 7B runs (2026-08-01/02) produced a settings.py that used
BASE_DIR in DATABASES without ever defining it, failing `manage.py check`,
failing M-001, and leaving all 23 milestones pending.
"""
from __future__ import annotations

import ast

from shamsu.prd.boilerplate import (
    django_layout,
    is_django_project,
    is_node_express_project,
    is_react_vite_project,
    render_boilerplate,
    uses_postgres_runtime,
)

EXPECTED = [
    "backend/config/__init__.py",
    "backend/config/settings.py",
    "backend/config/urls.py",
    "backend/core/__init__.py",
    "backend/core/apps.py",
    "backend/core/migrations/__init__.py",
    "backend/core/models.py",
    "backend/manage.py",
    "backend/requirements.txt",
]


def test_layout_is_inferred_from_expected_files():
    assert is_django_project(EXPECTED) is True
    assert django_layout(EXPECTED) == ("config", "core")


def test_generated_settings_defines_base_dir_before_using_it():
    """The exact 6/6 live defect."""
    content = render_boilerplate("backend/config/settings.py", EXPECTED)

    assert content is not None
    assert "BASE_DIR = Path(__file__).resolve().parent.parent" in content
    body = content.splitlines()
    define = next(i for i, line in enumerate(body) if line.startswith("BASE_DIR ="))
    use = next(i for i, line in enumerate(body) if "BASE_DIR / \"db.sqlite3\"" in line)
    assert define < use
    # Valid Python, and every name used at module level is bound.
    ast.parse(content)


def test_generated_settings_pulls_in_no_uninstalled_dependencies():
    """The full SETTINGS_TEMPLATE installs rest_framework/simplejwt/crispy;
    using it here would swap a NameError for a ModuleNotFoundError, since the
    milestone verifier runs `manage.py check` against the ambient Django."""
    content = render_boilerplate("backend/config/settings.py", EXPECTED)

    for package in ("rest_framework", "crispy_forms", "crispy_tailwind", "simplejwt"):
        assert package not in content
    assert '"core",' in content


def test_generated_settings_wires_a_custom_user_model_only_when_asked():
    with_user = render_boilerplate(
        "backend/config/settings.py", EXPECTED, custom_user_model=True
    )
    without = render_boilerplate("backend/config/settings.py", EXPECTED)

    assert 'AUTH_USER_MODEL = "core.User"' in with_user
    assert "AUTH_USER_MODEL" not in without


def test_wsgi_application_is_set_only_when_the_module_is_created():
    """Live run 7: settings pointed at config.wsgi.application while wsgi.py was
    never in expected_files, and the architecture validator correctly rejected
    it ("WSGI module does not exist"). manage.py check does not need it."""
    without = render_boilerplate("backend/config/settings.py", EXPECTED)
    with_wsgi = render_boilerplate(
        "backend/config/settings.py", [*EXPECTED, "backend/config/wsgi.py"]
    )

    assert "WSGI_APPLICATION" not in without
    assert 'WSGI_APPLICATION = "config.wsgi.application"' in with_wsgi
    ast.parse(without)
    ast.parse(with_wsgi)


def test_manage_and_urls_and_apps_are_generated_and_parse():
    manage = render_boilerplate("backend/manage.py", EXPECTED)
    urls = render_boilerplate("backend/config/urls.py", EXPECTED)
    apps = render_boilerplate("backend/core/apps.py", EXPECTED)

    assert manage is not None and "config.settings" in manage
    assert urls is not None and "admin.site.urls" in urls
    assert apps is not None and "class CoreConfig(AppConfig)" in apps
    for content in (manage, urls, apps):
        ast.parse(content)


def test_root_urls_include_the_app_only_when_app_urls_are_expected():
    without = render_boilerplate("backend/config/urls.py", EXPECTED)
    with_app = render_boilerplate(
        "backend/config/urls.py", [*EXPECTED, "backend/core/urls.py"]
    )

    assert "include(" not in without
    assert 'include("core.urls")' in with_app


def test_product_logic_is_left_to_the_model():
    """models.py/views.py carry product decisions - the model does these well
    and must keep them."""
    assert render_boilerplate("backend/core/models.py", EXPECTED) is None
    assert render_boilerplate("backend/core/views.py", EXPECTED) is None


def test_non_django_projects_are_untouched():
    node = ["src/App.tsx", "package.json"]

    assert is_django_project(node) is False
    assert render_boilerplate("src/App.tsx", node) is None


def test_django_runtime_files_are_generated_deterministically():
    requirements = render_boilerplate("backend/requirements.txt", EXPECTED)

    assert requirements is not None
    assert "Django" in requirements
    assert "psycopg" in requirements
    assert render_boilerplate("backend/Dockerfile", [*EXPECTED, "backend/Dockerfile"]) is not None
    assert render_boilerplate("backend/.env.example", [*EXPECTED, "backend/.env.example"]) is not None


def test_postgres_runtime_switches_django_settings_off_sqlite():
    expected = [
        *EXPECTED,
        "docker-compose.yml",
        ".env.example",
        "backend/Dockerfile",
        "backend/.env.example",
    ]

    settings = render_boilerplate("backend/config/settings.py", expected)
    compose = render_boilerplate("docker-compose.yml", expected)

    assert uses_postgres_runtime(expected)
    assert settings is not None
    assert "django.db.backends.postgresql" in settings
    assert "db.sqlite3" not in settings
    assert compose is not None
    assert "postgres:" in compose
    assert "backend:" in compose
    assert "frontend:" not in compose
    assert "condition: service_healthy" in compose
    ast.parse(settings)


def test_full_stack_compose_includes_frontend_when_frontend_runtime_is_expected():
    expected = [
        *EXPECTED,
        "docker-compose.yml",
        ".env.example",
        "backend/Dockerfile",
        "backend/.env.example",
        "frontend/Dockerfile",
        "frontend/package.json",
    ]

    compose = render_boilerplate("docker-compose.yml", expected)

    assert compose is not None
    assert "postgres:" in compose
    assert "backend:" in compose
    assert "frontend:" in compose
    assert "context: ./frontend" in compose


def test_react_vite_runtime_files_are_generated_deterministically():
    expected = [
        "frontend/package.json",
        "frontend/index.html",
        "frontend/vite.config.ts",
        "frontend/.env.example",
        "frontend/Dockerfile",
        "frontend/src/main.tsx",
        "frontend/src/App.tsx",
    ]

    assert is_react_vite_project(expected)
    assert '"dev": "vite --host 0.0.0.0"' in render_boilerplate(
        "frontend/package.json", expected
    )
    assert 'src/main.tsx' in render_boilerplate("frontend/index.html", expected)
    assert "http://backend:8000" in render_boilerplate("frontend/vite.config.ts", expected)
    assert "VITE_API_BASE_URL=/api" in render_boilerplate("frontend/.env.example", expected)
    assert "node:22-alpine" in render_boilerplate("frontend/Dockerfile", expected)


def test_node_express_runtime_files_are_generated_deterministically():
    expected = [
        "backend/package.json",
        "backend/server.js",
        "backend/src/app.js",
        "backend/src/db.js",
        "backend/src/routes/index.js",
        "backend/src/schema.sql",
        "backend/.env.example",
        "backend/Dockerfile",
    ]

    assert is_node_express_project(expected)
    assert '"start": "node server.js"' in render_boilerplate("backend/package.json", expected)
    assert 'require("./src/app")' in render_boilerplate("backend/server.js", expected)
    assert 'app.use("/api", routes)' in render_boilerplate("backend/src/app.js", expected)
    assert 'require("pg")' in render_boilerplate("backend/src/db.js", expected)
    assert 'router.get("/listings"' in render_boilerplate(
        "backend/src/routes/index.js", expected
    )
    assert "CREATE TABLE IF NOT EXISTS listings" in render_boilerplate(
        "backend/src/schema.sql", expected
    )
    assert "DATABASE_URL=sqlite:./db.sqlite3" in render_boilerplate(
        "backend/.env.example", expected
    )
    assert 'CMD ["npm", "start"]' in render_boilerplate("backend/Dockerfile", expected)


def test_node_express_runtime_uses_postgres_when_compose_is_expected():
    expected = [
        "docker-compose.yml",
        ".env.example",
        "backend/package.json",
        "backend/server.js",
        "backend/.env.example",
        "backend/Dockerfile",
    ]

    package = render_boilerplate("backend/package.json", expected)
    env = render_boilerplate("backend/.env.example", expected)
    compose = render_boilerplate("docker-compose.yml", expected)

    assert package is not None and '"pg"' in package
    assert env is not None and "postgres://openbazaar" in env
    assert compose is not None and "DATABASE_URL: postgres://openbazaar" in compose


def test_react_index_html_matches_jsx_entrypoint_when_that_is_expected():
    expected = [
        "frontend/package.json",
        "frontend/index.html",
        "frontend/vite.config.ts",
        "frontend/src/main.jsx",
        "frontend/src/App.jsx",
    ]

    html = render_boilerplate("frontend/index.html", expected)

    assert html is not None
    assert 'src/main.jsx' in html
    assert 'src/main.tsx' not in html


def test_runtime_boilerplate_handles_expected_files_under_project_root():
    expected = [
        "openbazaar/docker-compose.yml",
        "openbazaar/.env.example",
        "openbazaar/backend/manage.py",
        "openbazaar/backend/requirements.txt",
        "openbazaar/backend/config/settings.py",
        "openbazaar/backend/Dockerfile",
        "openbazaar/backend/.env.example",
        "openbazaar/frontend/package.json",
        "openbazaar/frontend/index.html",
        "openbazaar/frontend/vite.config.ts",
        "openbazaar/frontend/Dockerfile",
        "openbazaar/frontend/src/main.jsx",
    ]

    assert uses_postgres_runtime(expected)
    assert is_react_vite_project(expected)
    assert render_boilerplate("openbazaar/docker-compose.yml", expected) is not None
    assert render_boilerplate("openbazaar/backend/Dockerfile", expected) is not None
    assert render_boilerplate("openbazaar/backend/package.json", [
        "openbazaar/backend/package.json",
        "openbazaar/backend/server.js",
    ]) is not None
    html = render_boilerplate("openbazaar/frontend/index.html", expected)

    assert html is not None
    assert "src/main.jsx" in html
