"""Django scaffolding is generated by substitution, never written by the model.

Six consecutive live 7B runs (2026-08-01/02) produced a settings.py that used
BASE_DIR in DATABASES without ever defining it, failing `manage.py check`,
failing M-001, and leaving all 23 milestones pending.
"""
from __future__ import annotations

import ast

from shamsu.prd.boilerplate import (
    django_layout,
    is_django_project,
    render_boilerplate,
)

EXPECTED = [
    "backend/config/__init__.py",
    "backend/config/settings.py",
    "backend/config/urls.py",
    "backend/core/__init__.py",
    "backend/core/apps.py",
    "backend/core/migrations/__init__.py",
    "backend/core/models.py",
    "backend/manage.py",
    "backend/requirements.txt",
]


def test_layout_is_inferred_from_expected_files():
    assert is_django_project(EXPECTED) is True
    assert django_layout(EXPECTED) == ("config", "core")


def test_generated_settings_defines_base_dir_before_using_it():
    """The exact 6/6 live defect."""
    content = render_boilerplate("backend/config/settings.py", EXPECTED)

    assert content is not None
    assert "BASE_DIR = Path(__file__).resolve().parent.parent" in content
    body = content.splitlines()
    define = next(i for i, line in enumerate(body) if line.startswith("BASE_DIR ="))
    use = next(i for i, line in enumerate(body) if "BASE_DIR / \"db.sqlite3\"" in line)
    assert define < use
    # Valid Python, and every name used at module level is bound.
    ast.parse(content)


def test_generated_settings_pulls_in_no_uninstalled_dependencies():
    """The full SETTINGS_TEMPLATE installs rest_framework/simplejwt/crispy;
    using it here would swap a NameError for a ModuleNotFoundError, since the
    milestone verifier runs `manage.py check` against the ambient Django."""
    content = render_boilerplate("backend/config/settings.py", EXPECTED)

    for package in ("rest_framework", "crispy_forms", "crispy_tailwind", "simplejwt"):
        assert package not in content
    assert '"core",' in content


def test_generated_settings_wires_a_custom_user_model_only_when_asked():
    with_user = render_boilerplate(
        "backend/config/settings.py", EXPECTED, custom_user_model=True
    )
    without = render_boilerplate("backend/config/settings.py", EXPECTED)

    assert 'AUTH_USER_MODEL = "core.User"' in with_user
    assert "AUTH_USER_MODEL" not in without


def test_wsgi_application_is_set_only_when_the_module_is_created():
    """Live run 7: settings pointed at config.wsgi.application while wsgi.py was
    never in expected_files, and the architecture validator correctly rejected
    it ("WSGI module does not exist"). manage.py check does not need it."""
    without = render_boilerplate("backend/config/settings.py", EXPECTED)
    with_wsgi = render_boilerplate(
        "backend/config/settings.py", [*EXPECTED, "backend/config/wsgi.py"]
    )

    assert "WSGI_APPLICATION" not in without
    assert 'WSGI_APPLICATION = "config.wsgi.application"' in with_wsgi
    ast.parse(without)
    ast.parse(with_wsgi)


def test_manage_and_urls_and_apps_are_generated_and_parse():
    manage = render_boilerplate("backend/manage.py", EXPECTED)
    urls = render_boilerplate("backend/config/urls.py", EXPECTED)
    apps = render_boilerplate("backend/core/apps.py", EXPECTED)

    assert manage is not None and "config.settings" in manage
    assert urls is not None and "admin.site.urls" in urls
    assert apps is not None and "class CoreConfig(AppConfig)" in apps
    for content in (manage, urls, apps):
        ast.parse(content)


def test_root_urls_include_the_app_only_when_app_urls_are_expected():
    without = render_boilerplate("backend/config/urls.py", EXPECTED)
    with_app = render_boilerplate(
        "backend/config/urls.py", [*EXPECTED, "backend/core/urls.py"]
    )

    assert "include(" not in without
    assert 'include("core.urls")' in with_app


def test_product_logic_is_left_to_the_model():
    """models.py/views.py carry product decisions - the model does these well
    and must keep them."""
    assert render_boilerplate("backend/core/models.py", EXPECTED) is None
    assert render_boilerplate("backend/core/views.py", EXPECTED) is None
    assert render_boilerplate("backend/requirements.txt", EXPECTED) is None


def test_non_django_projects_are_untouched():
    node = ["src/App.tsx", "package.json"]

    assert is_django_project(node) is False
    assert render_boilerplate("src/App.tsx", node) is None
