"""Repository artifacts, built once per run and selected per step.

Plan §15 asks for compact artifacts — repository maps, module cards, symbol
cards, dependency and test maps — retrieved *first*, with raw source loaded only
when necessary. It calls this the single most important thing for making a small
model work on a large codebase.

All of it was written and none of it ran. `ArtifactRegistry`, the twelve
`ArtifactKind`s, the generators, the content hashing, the staleness state
machine and `ArtifactRefresher` were constructed only in tests;
`FrameInputs.artifacts` was defined, rendered by the compiler complete with
stale labelling, and never populated. The agent worked from grep on every step.

This module is the seam that was missing. Two jobs:

**Refresh once per run.** Content hashes decide what is rebuilt, so an
unchanged repository costs a scan and nothing else. `recompute_status` runs
first, which is what makes a stale card *say* it is stale rather than quietly
being wrong.

**Select for the step, not for the repository.** A four-hundred-card registry
helps nobody if all four hundred reach the frame. What goes in is the card for
each file the step names and the card for each symbol it mentions — the same
narrowing `grounding.py` does, one level up: grounding says *where* the code is,
a module card says *what it does*.

Two properties this must hold, and both are the reason it is a separate module
rather than a few lines in `session.py`:

* **Stale artifacts still flow.** The compiler labels them and warns. Invariant
  4 is that stale context may reach the model *only* labelled — not that it is
  withheld, because "SHAMSU used to believe X" is often what a user needs.
* **Nothing here may fail a run.** A refresh that raises, a registry that
  cannot write, a repository too large to scan — every one of those yields no
  artifacts and a run that proceeds exactly as it did before this existed.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from shamsu.artifacts.refresh import ArtifactRefresher
from shamsu.artifacts.registry import ArtifactRegistry
from shamsu.interfaces.artifacts import Artifact
from shamsu.interfaces.cancellation import CancellationToken, Cancelled
from shamsu.interfaces.enums import ArtifactKind
from shamsu.interfaces.ids import ProjectId
from shamsu.security.paths import workspace_key
from shamsu.state.records import PlanStepRecord
from shamsu.state.store import StateStore

#: Cards allowed into one frame. The budget the compiler enforces is in tokens;
#: this is the cruder bound that stops a step naming six files from crowding out
#: the step itself before the compiler ever gets to choose.
MAX_ARTIFACTS_PER_FRAME = 6

#: Repositories larger than this are not refreshed inside a run. Generating a
#: card per module across a very large tree is minutes of work, and a task that
#: appears to hang on its first decision is worse than one with no cards.
MAX_FILES_TO_REFRESH = 1_500

#: What a run builds. Deliberately not every kind: these are the ones a coding
#: step reads. Dependency, API, test and schema maps are generated by the same
#: refresher when their generators are wired, and adding them here without a
#: selection rule would only spend budget.
RUN_KINDS: tuple[ArtifactKind, ...] = (
    ArtifactKind.REPOSITORY_MAP,
    ArtifactKind.MODULE_CARD,
    ArtifactKind.SYMBOL_CARD,
)


class ProjectKnowledge:
    """A project's artifacts: refreshed once, then queried per step."""

    def __init__(
        self,
        store: StateStore,
        project_id: ProjectId,
        workspace: Path,
        *,
        use_git: bool = True,
    ) -> None:
        self._workspace = Path(workspace).resolve()
        self._registry = ArtifactRegistry(
            store, project_id, self._workspace / ".shamsu" / "artifacts"
        )
        self._refresher = ArtifactRefresher(self._registry, self._workspace, use_git=use_git)
        self._ready = False

    @property
    def registry(self) -> ArtifactRegistry:
        return self._registry

    @property
    def ready(self) -> bool:
        """Whether a refresh has succeeded. False means "no cards", never an error."""
        return self._ready

    def refresh(self, *, cancel: CancellationToken | None = None, file_count: int = 0) -> str:
        """Bring the artifact set up to date. Returns a one-line report.

        Never raises except for `Cancelled`, which must propagate — a run the
        user stopped has to stop, and swallowing it here would leave a refresh
        grinding on after cancellation.
        """
        if file_count and file_count > MAX_FILES_TO_REFRESH:
            return f"artifacts skipped: {file_count} files exceeds the {MAX_FILES_TO_REFRESH} cap"

        try:
            report = self._refresher.refresh(kinds=RUN_KINDS, cancel=cancel)
        except Cancelled:
            raise
        except Exception as exc:  # noqa: BLE001 - artifacts must never fail a run
            return f"artifacts unavailable ({type(exc).__name__}: {exc})"

        self._ready = True
        return report.summary()

    def for_step(self, step: PlanStepRecord) -> tuple[Artifact, ...]:
        """The cards worth showing this step, most specific first.

        Symbol cards before module cards before the repository map: the
        narrowest thing that answers the question should win the budget, and
        the compiler trims from the bottom.
        """
        if not self._ready:
            return ()

        try:
            return self._select(step)
        except Exception:  # noqa: BLE001 - a missing card beats a dead run
            return ()

    # -- internals ---------------------------------------------------------

    def _select(self, step: PlanStepRecord) -> tuple[Artifact, ...]:
        wanted: list[Artifact] = []
        seen: set[tuple[str, str]] = set()

        def take(kind: ArtifactKind, key: str) -> None:
            if len(wanted) >= MAX_ARTIFACTS_PER_FRAME or (kind.value, key) in seen:
                return
            seen.add((kind.value, key))
            # `usable` rather than `get`: an artifact whose generation failed,
            # or which was retired because its source is gone, must not reach a
            # frame at all. A *stale* one still may — labelled.
            artifact = self._registry.usable(kind, key)
            if artifact is not None:
                wanted.append(artifact)

        files = [workspace_key(path) for path in step.inputs]

        # Symbol cards for the files this step names. Keyed `path::qualified`,
        # so they are found by listing the kind and filtering rather than by
        # guessing a symbol name the step never spelled out.
        for meta in self._registry.list_by_kind(ArtifactKind.SYMBOL_CARD):
            if len(wanted) >= MAX_ARTIFACTS_PER_FRAME:
                break
            owner, _, _ = meta.key.partition("::")
            if workspace_key(owner) in files:
                take(ArtifactKind.SYMBOL_CARD, meta.key)

        for path in files:
            take(ArtifactKind.MODULE_CARD, path)

        return tuple(wanted)

    def stale_summary(self) -> str:
        """What is known to be out of date, for the run report."""
        if not self._ready:
            return ""
        stale = self._registry.stale()
        if not stale:
            return ""
        names = ", ".join(sorted(meta.key for meta in stale)[:5])
        return f"{len(stale)} artifact(s) are stale: {names}"


def file_count(paths: Sequence[str]) -> int:
    """Convenience for callers that already scanned the repository."""
    return len(paths)


__all__ = [
    "MAX_ARTIFACTS_PER_FRAME",
    "MAX_FILES_TO_REFRESH",
    "RUN_KINDS",
    "ProjectKnowledge",
    "file_count",
]
