"""Archetype template registry.

The v2.2 architecture treats Django as one provider behind a registry instead
of the whole generation system. This wrapper is intentionally thin for now:
existing deterministic Django renderers stay in place while typed-hole
generation can be added provider-by-provider.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from shamsu.templates.django.checker import BackendConsistencyChecker
from shamsu.templates.django.docs import render_generated_project_readme
from shamsu.templates.django.frontend import render_django_test_files, render_frontend_django_files
from shamsu.templates.django.generators import render_backend_django_files
from shamsu.templates.django.renderer import render_fixed_django_files
from shamsu.types import Archetype, GenerationManifest, Hole, ProjectSpec


class TemplateProvider(Protocol):
    archetype: Archetype

    def smoke_test(self) -> bool: ...

    def build_manifest(self, project: ProjectSpec) -> GenerationManifest: ...

    def render_fixed(self, project: ProjectSpec) -> dict[str, str]: ...

    def render_all(self, project: ProjectSpec) -> dict[str, str]: ...


@dataclass(frozen=True)
class DjangoTemplateProvider:
    archetype: Archetype

    def smoke_test(self) -> bool:
        return True

    def build_manifest(self, project: ProjectSpec) -> GenerationManifest:
        holes = [
            Hole(
                id=f"django:{file.path}",
                hole_type=file.generator,
                target_file=file.path,
                description=f"Generate {file.path} using {file.generator}.",
                depends_on=file.depends_on,
                specialist=file.specialist or "template",
            )
            for file in project.generation_order
            if file.specialist is not None
        ]
        return GenerationManifest(holes=holes)

    def render_fixed(self, project: ProjectSpec) -> dict[str, str]:
        return render_fixed_django_files(project)

    def render_all(self, project: ProjectSpec) -> dict[str, str]:
        return {
            **render_fixed_django_files(project),
            **render_backend_django_files(project),
            **render_frontend_django_files(project),
            **render_django_test_files(project),
            "README.md": render_generated_project_readme(project),
        }


@dataclass(frozen=True)
class GenericWebTemplateProvider:
    archetype: Archetype = Archetype.GENERIC_WEB

    def smoke_test(self) -> bool:
        return True

    def build_manifest(self, project: ProjectSpec) -> GenerationManifest:
        return GenerationManifest()

    def render_fixed(self, project: ProjectSpec) -> dict[str, str]:
        return self.render_all(project)

    def render_all(self, project: ProjectSpec) -> dict[str, str]:
        title = project.project_name.replace("_", " ").title()
        return {
            "index.html": (
                "<!doctype html>\n"
                "<html lang=\"en\">\n"
                "<head><meta charset=\"utf-8\"><title>"
                f"{title}</title></head>\n"
                f"<body><main><h1>{title}</h1><p>Generated generic web scaffold.</p></main></body>\n"
                "</html>\n"
            ),
            "README.md": f"# {title}\n\nGeneric web scaffold generated by SHAMSU.\n",
        }


_PROVIDERS: dict[Archetype, TemplateProvider] = {
    Archetype.WEB_CRUD: DjangoTemplateProvider(Archetype.WEB_CRUD),
    Archetype.REST_API: DjangoTemplateProvider(Archetype.REST_API),
    Archetype.GENERIC_WEB: GenericWebTemplateProvider(),
}


def get_template_provider(archetype: Archetype) -> TemplateProvider:
    return _PROVIDERS.get(archetype, _PROVIDERS[Archetype.GENERIC_WEB])


def backend_checker_for(archetype: Archetype):
    if archetype in {Archetype.WEB_CRUD, Archetype.REST_API}:
        return BackendConsistencyChecker
    return None
