"""Generated-project documentation renderers."""

from __future__ import annotations

from shamsu.types import ProjectSpec


def render_generated_project_readme(project: ProjectSpec) -> str:
    return f"""# {project.project_name.replace("_", " ").title()}

Generated by SHAMSU from a PRD.

## Install

```bash
python -m venv .venv
. .venv/bin/activate
pip install -r requirements.txt
```

On Windows PowerShell:

```powershell
python -m venv .venv
.\\.venv\\Scripts\\Activate.ps1
pip install -r requirements.txt
```

## Migrate

```bash
python manage.py makemigrations
python manage.py migrate
```

## Test

```bash
python manage.py test --verbosity=2
```

## Run

```bash
python manage.py runserver
```

## Generated App

- Django project: `{project.project_name}`
- Django app: `{project.app_name}`
- DaisyUI theme: `{project.theme}`
- Entities: {", ".join(entity.name for entity in project.entities) or "none"}
"""


def render_pipeline_summary(result) -> str:
    project_name = result.project.project_name if result.project else "unknown"
    generated = "\n".join(f"- {path}" for path in (result.written_files or [])) or "- none"
    diagnostics = (
        "\n".join(
            f"- {item.file_path}: {item.symbol} - {item.message}"
            for item in (result.diagnostics or [])
        )
        or "- none"
    )
    setup = "not run"
    if result.setup_result:
        setup = "ok" if result.setup_result.ok else "failed"
    tests = "not run"
    if result.test_result:
        tests = f"{result.test_result.passed} passed, {result.test_result.failed} failed"
    feedback = "not run"
    if result.feedback_result:
        feedback = "success" if result.feedback_result.success else result.feedback_result.error
    dod = "not run"
    if getattr(result, "dod_result", None):
        failures = result.dod_result.required_failures
        unverified = result.dod_result.required_unverified
        if failures:
            dod = "failed: " + ", ".join(item.item_id for item in failures)
        elif unverified:
            dod = "unverified: " + ", ".join(item.item_id for item in unverified)
        else:
            dod = "ok"
    preview = getattr(result, "preview_url", "") or "not available"
    return f"""# SHAMSU Generation Summary

## Result

- Project: `{project_name}`
- Target: `{result.target_dir}`
- Success: `{result.success}`
- Error: {result.error or "none"}

## Commands And Checks

- Setup: {setup}
- Tests: {tests}
- Feedback loop: {feedback}
- Definition of Done: {dod}
- Preview URL: {preview}

## Generated Files

{generated}

## Remaining Warnings

{diagnostics}
"""
