"""Forced category tech stacks for small-local-model reliability."""
from __future__ import annotations

from dataclasses import dataclass, field

from shamsu.registry.schema import Category


@dataclass(frozen=True)
class StackPolicy:
    category: Category
    frontend: str
    styling: str
    backend: str
    database: str
    build: str
    required_packages: list[str] = field(default_factory=list)
    model_job: list[str] = field(default_factory=list)
    template_owns: list[str] = field(default_factory=list)


STACK_POLICIES: dict[Category, StackPolicy] = {
    Category.MULTIPLAYER_GAME: StackPolicy(
        category=Category.MULTIPLAYER_GAME,
        frontend="React + React-Three-Fiber + Three.js",
        styling="CSS modules/plain CSS inside Vite template",
        backend="Prebuilt Colyseus relay room server; not regenerated by the model",
        database="none",
        build="Vite + TypeScript",
        required_packages=[
            "react",
            "react-dom",
            "three",
            "@react-three/fiber",
            "colyseus",
            "colyseus.js",
            "@dimforge/rapier3d-compat",
            "vite",
            "typescript",
        ],
        model_job=[
            "entity schemas",
            "game rules",
            "spawn/collision/end-condition logic",
            "HUD bindings",
        ],
        template_owns=[
            "main menu",
            "lobby",
            "Colyseus relay plumbing",
            "render loop",
            "player sync",
            "test IDs",
        ],
    ),
    Category.PORTFOLIO_SITE: StackPolicy(
        category=Category.PORTFOLIO_SITE,
        frontend="SvelteKit",
        styling="TailwindCSS",
        backend="none",
        database="Markdown + frontmatter",
        build="Vite through SvelteKit",
        required_packages=["@sveltejs/kit", "svelte", "tailwindcss", "vite"],
        model_job=["content files", "project metadata", "hero/nav/theme tokens"],
        template_owns=["routing", "layout", "gallery", "contact form", "dark mode"],
    ),
    Category.MULTI_TENANT_ADMIN: StackPolicy(
        category=Category.MULTI_TENANT_ADMIN,
        frontend="Next.js + React + TypeScript",
        styling="shadcn/ui + TailwindCSS",
        backend="Next.js API routes",
        database="PostgreSQL + Prisma",
        build="Next.js",
        required_packages=["next", "react", "typescript", "prisma", "next-auth", "tailwindcss"],
        model_job=["Prisma entity additions", "CRUD route holes", "dashboard widgets", "RBAC rules"],
        template_owns=["auth", "tenant model", "role checks", "dashboard shell", "shadcn components"],
    ),
    Category.ECOMMERCE: StackPolicy(
        category=Category.ECOMMERCE,
        frontend="Next.js + React + TypeScript",
        styling="shadcn/ui + TailwindCSS",
        backend="Next.js API routes with Stripe hosted checkout",
        database="Static catalog or PostgreSQL + Prisma when inventory is required",
        build="Next.js",
        required_packages=["next", "react", "typescript", "stripe", "zustand", "tailwindcss"],
        model_job=["product data", "product/cart UI holes", "checkout copy", "optional inventory logic"],
        template_owns=["Stripe redirect", "webhook shell", "cart store", "product grid", "confirmation page"],
    ),
    Category.GENERAL_WEB: StackPolicy(
        category=Category.GENERAL_WEB,
        frontend="SvelteKit",
        styling="TailwindCSS",
        backend="none by default; SvelteKit endpoints only when required",
        database="Markdown/frontmatter or static JSON",
        build="Vite through SvelteKit",
        required_packages=["@sveltejs/kit", "svelte", "tailwindcss", "vite"],
        model_job=["pages", "forms", "content", "small integrations"],
        template_owns=["routing", "layout", "responsive shell", "contact form"],
    ),
}


def stack_policy_for(category: Category | str) -> StackPolicy:
    resolved = Category(category)
    if resolved in {Category.WEB_CRUD, Category.REST_API}:
        return StackPolicy(
            category=resolved,
            frontend="Django templates + DaisyUI + HTMX",
            styling="DaisyUI/Tailwind via CDN",
            backend="Django + Django REST Framework",
            database="SQLite default, Django ORM",
            build="Python manage.py",
            required_packages=["django", "djangorestframework", "crispy-forms", "django-htmx"],
            model_job=["models", "serializers", "forms", "views", "templates", "tests"],
            template_owns=["settings", "urls", "auth shell", "base templates"],
        )
    return STACK_POLICIES[resolved]
